### ISSUE TITLE
Warn if PR is against non-standard branch

### ISSUE THREAD

**Issue by edunham** [nrc/highfive#50]
For most repos, there's one branch that most PRs are expected to be filed against. 

```
17:11:54 <@brson> this patch was submitted against 'stable' https://github.com/rust-lang/rust/pull/25739 but thankfully bors merged it into master
17:12:22 <@acrichto> brson: whoa
17:12:45 <@acrichto> brson: I wonder if rust-highfive could give a warning if it's not targeting master
```
The API contains information on which branch a PR was submitted against, in the form of "base"["label"]. For instance, grep `rust-lang:stable` in the result of `curl -i https://api.github.com/repos/rust-lang/rust/pulls/25739`. 

I believe the architecture for this would be to add an `expected_branch` field in each repo's config, then add the check to highfive and default to assuming the expected branch is `<reponame>:master` if none is specified? 

If this is something you'd like to get added, I can implement it.

**Comment by nrc** [comment]
Sure, sounds like a good thing to add and the plan sounds good
